@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
	"name": "name",
	"email":"name@email.com",
	"password": "123456"
}
###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"email":"name@email.com",
	"password": "123456"
}
###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"title":"new titles",
	"content": "text example text example text example text example text example text example"
}
###
# @name fetch_recent_questions
GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

